name: Continous Integration

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: [self-hosted, deploy]
    outputs:
      image_version: ${{ steps.subscriber_meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Restore node_modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: ./node_modules
          key: node-cache-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

      - name: Set Node version
        uses: actions/setup-node@v3
        with:
          node-version: "13"

      - name: Install NPM dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Unit Tests
        run: npm run test

      - name: TSLint
        run: npm run tslint

      - name: build
        run: npm build
